spring:
  redis:
    host: 121.199.57.24
    password: 123456
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/zs_im?serverTimezone=UTC
    username: root
    password: dream
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
server:
  port: 8099
mybatis-plus:
  type-aliases-package: com.eleven
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
oauth2:
  clientId: admin
  secret: elevenZ
ease:
  clientId: YXA6zl0MsW5YTQ6JFVFGUTFgeA
  clientSecret: YXA6fN-mBR5MvYCtlqVwLOfyjwgDP5Q
  appKey: 1102210107065543#alumni
  orgName: 1102210107065543
  appName: alumni
  restApi: https://a1.easemob.com
  tokenUrl: https://a1.easemob.com/1102210107065543/alumni
